title: Rosswell Cabrera
#logo: /assets/image.png
#description: Text below image
remote_theme: tuur29/pages-themes-cayman
css: /assets/css/style.scss
buttons:
      zip_url: http://example.com/
      zip_title: Title
      zip_hide: true
      tar_url: http://example.com/
      tar_title: Title
      tar_hide: true
      github_hide: true # hides "View on Github"
colors:
    gradient_left: "#D64045"
    gradient_right: "#353A47"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
