title: Rosswell Cabrera
#logo: /assets/image.png
#description: Text below image
remote_theme: tuur29/pages-themes-cayman
css: /assets/css/style.scss
buttons:
      zip_url: http://example.com/
      zip_title: Title
      zip_hide: true
      tar_url: http://example.com/
      tar_title: Title
      tar_hide: true
      github_hide: true # hides "View on Github"
color:
  header: "#FFF"
  gradient_left: "#7D7ABC"
  gradient_right: "#D64045"
  link: "#1e6bb8"
